### ISSUE TITLE
Small feedback

### ISSUE THREAD

**Issue by Domosed-gamin** [dead-end/nuzzle#4]
Wow mate! It is little masterpiece! I love games for linux terminal. Thank you for shared source and free license for it. Only maybe add keyboard control. Mouse is good. But keyboard for terminal is better. Is it possible?

**Comment by dead-end** [comment]
I had implemented keyboard control at the beginning, but I thought that playing with the keyboard was a little arduous. I think I can start a second try.

**Comment by dead-end** [comment]
Implemented in v0.2

(https://github.com/dead-end/nuzzle/releases/tag/v0.2)

**Comment by Domosed-gamin** [comment]
Cool. I like keyboard control. This is comfortably.
